// flow-typed signature: 9cead56a9308ee4cc4e811ce37bba1fe
// flow-typed version: <<STUB>>/express_v4.16.4/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express/lib/application' {
  declare module.exports: any;
}

declare module 'express/lib/express' {
  declare module.exports: any;
}

declare module 'express/lib/middleware/init' {
  declare module.exports: any;
}

declare module 'express/lib/middleware/query' {
  declare module.exports: any;
}

declare module 'express/lib/request' {
  declare module.exports: any;
}

declare module 'express/lib/response' {
  declare module.exports: any;
}

declare module 'express/lib/router/index' {
  declare module.exports: any;
}

declare module 'express/lib/router/layer' {
  declare module.exports: any;
}

declare module 'express/lib/router/route' {
  declare module.exports: any;
}

declare module 'express/lib/utils' {
  declare module.exports: any;
}

declare module 'express/lib/view' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express/index' {
  declare module.exports: $Exports<'express'>;
}
declare module 'express/index.js' {
  declare module.exports: $Exports<'express'>;
}
declare module 'express/lib/application.js' {
  declare module.exports: $Exports<'express/lib/application'>;
}
declare module 'express/lib/express.js' {
  declare module.exports: $Exports<'express/lib/express'>;
}
declare module 'express/lib/middleware/init.js' {
  declare module.exports: $Exports<'express/lib/middleware/init'>;
}
declare module 'express/lib/middleware/query.js' {
  declare module.exports: $Exports<'express/lib/middleware/query'>;
}
declare module 'express/lib/request.js' {
  declare module.exports: $Exports<'express/lib/request'>;
}
declare module 'express/lib/response.js' {
  declare module.exports: $Exports<'express/lib/response'>;
}
declare module 'express/lib/router/index.js' {
  declare module.exports: $Exports<'express/lib/router/index'>;
}
declare module 'express/lib/router/layer.js' {
  declare module.exports: $Exports<'express/lib/router/layer'>;
}
declare module 'express/lib/router/route.js' {
  declare module.exports: $Exports<'express/lib/router/route'>;
}
declare module 'express/lib/utils.js' {
  declare module.exports: $Exports<'express/lib/utils'>;
}
declare module 'express/lib/view.js' {
  declare module.exports: $Exports<'express/lib/view'>;
}
