// flow-typed signature: 39fce8995cd032799bc0ffb3154f67fd
// flow-typed version: <<STUB>>/next-routes_v1.4.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-routes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-routes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-routes/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-routes/dist/index.js' {
  declare module.exports: $Exports<'next-routes/dist/index'>;
}
