// flow-typed signature: 512999c7ac6ce47f0bedccedfb7a2ede
// flow-typed version: <<STUB>>/next-nprogress_v1.4.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-nprogress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-nprogress' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-nprogress/component' {
  declare module.exports: any;
}

declare module 'next-nprogress/dist/component' {
  declare module.exports: any;
}

declare module 'next-nprogress/dist/hoc' {
  declare module.exports: any;
}

declare module 'next-nprogress/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-nprogress/component.js' {
  declare module.exports: $Exports<'next-nprogress/component'>;
}
declare module 'next-nprogress/dist/component.js' {
  declare module.exports: $Exports<'next-nprogress/dist/component'>;
}
declare module 'next-nprogress/dist/hoc.js' {
  declare module.exports: $Exports<'next-nprogress/dist/hoc'>;
}
declare module 'next-nprogress/index' {
  declare module.exports: $Exports<'next-nprogress'>;
}
declare module 'next-nprogress/index.js' {
  declare module.exports: $Exports<'next-nprogress'>;
}
declare module 'next-nprogress/styles.js' {
  declare module.exports: $Exports<'next-nprogress/styles'>;
}
