// flow-typed signature: 4a5550bf1524e36b96247cd00383d1dd
// flow-typed version: <<STUB>>/react-clipboard.js_v2.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-clipboard.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-clipboard.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-clipboard.js/dist/react-clipboard' {
  declare module.exports: any;
}

declare module 'react-clipboard.js/dist/react-clipboard.min' {
  declare module.exports: any;
}

declare module 'react-clipboard.js/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-clipboard.js/dist/react-clipboard.js' {
  declare module.exports: $Exports<'react-clipboard.js/dist/react-clipboard'>;
}
declare module 'react-clipboard.js/dist/react-clipboard.min.js' {
  declare module.exports: $Exports<
    'react-clipboard.js/dist/react-clipboard.min'
  >;
}
declare module 'react-clipboard.js/index' {
  declare module.exports: $Exports<'react-clipboard.js'>;
}
declare module 'react-clipboard.js/index.js' {
  declare module.exports: $Exports<'react-clipboard.js'>;
}
declare module 'react-clipboard.js/webpack.config.js' {
  declare module.exports: $Exports<'react-clipboard.js/webpack.config'>;
}
